# Generated by Django 3.0.7 on 2020-08-23 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lupd_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pass_upd_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('login_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('signature', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(blank=True, unique=True)),
            ],
        ),
    ]
