# Generated by Django 3.1.1 on 2020-09-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
